name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login no GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build
        run: |
          docker build -t ghcr.io/rafaelghiorzi/flask-app:latest .

      - name: Push
        run: |
          docker push ghcr.io/rafaelghiorzi/flask-app:latest